export default {
	CREATE: "CREATE",
	CREATE_FILE: "CREATE FILE",
	CREATE_FOLDER: "CREATE FOLDER",
	DELETE_FILE: "DELETE FILE",
	DELETE_FOLDER: "DELETE FOLDER",
	DELETE_FOLDER_FORCE: { main: "DELETE", sub: "FORCE" },
	APPEND: { main: "APPEND TO", sub: "THIS CONTENT:" },
	WRITE: { main: "WRITE TO", sub: "THIS CONTENT:" },
	RENAME: { main: "RENAME", sub: "TO" },
};
